/** Studio Engine — Events */
export const STUDIO_EVENTS = {
  WORKSPACE_CREATED: 'studio.workspace.created',
  WORKSPACE_UPDATED: 'studio.workspace.updated',
  WORKSPACE_ARCHIVED: 'studio.workspace.archived',
  BUILD_SESSION_STARTED: 'studio.session.started',
  BUILD_SESSION_ENDED: 'studio.session.ended',
  THEME_ATTACHED: 'studio.theme.attached',
  COMPONENT_LIBRARY_ATTACHED: 'studio.component_library.attached',
  DRAFT_CREATED: 'studio.draft.created',
  DRAFT_UPDATED: 'studio.draft.updated',
  DRAFT_ARCHIVED: 'studio.draft.archived',
  COMPONENT_BINDING_ADDED: 'studio.component_binding.added',
  COMPONENT_BINDING_REMOVED: 'studio.component_binding.removed',
  CONTENT_BINDING_ADDED: 'studio.content_binding.added',
  CONTENT_BINDING_REMOVED: 'studio.content_binding.removed',
  DRAFT_VERIFIED: 'studio.draft.verified',
  DRAFT_PREVIEWED: 'studio.draft.previewed',
  PUBLISH_INTENT_CREATED: 'studio.publish.intent',
  PUBLISH_INTENT_PROCESSED: 'studio.publish.processed',
  PUBLISH_INTENT_FAILED: 'studio.publish.failed',
  PUBLISH_INTENT_CANCELLED: 'studio.publish.cancelled',
  ASSET_UPLOADED: 'studio.asset.uploaded',
  ASSET_ATTACHED: 'studio.asset.attached',
} as const;

export type StudioEventType = typeof STUDIO_EVENTS[keyof typeof STUDIO_EVENTS];

export const STUDIO_EVENT_SCHEMAS: Record<StudioEventType, string> = {
  'studio.workspace.created': 'studio.workspace.created.v1',
  'studio.workspace.updated': 'studio.workspace.updated.v1',
  'studio.workspace.archived': 'studio.workspace.archived.v1',
  'studio.session.started': 'studio.session.started.v1',
  'studio.session.ended': 'studio.session.ended.v1',
  'studio.theme.attached': 'studio.theme.attached.v1',
  'studio.component_library.attached': 'studio.component_library.attached.v1',
  'studio.draft.created': 'studio.draft.created.v1',
  'studio.draft.updated': 'studio.draft.updated.v1',
  'studio.draft.archived': 'studio.draft.archived.v1',
  'studio.component_binding.added': 'studio.component_binding.added.v1',
  'studio.component_binding.removed': 'studio.component_binding.removed.v1',
  'studio.content_binding.added': 'studio.content_binding.added.v1',
  'studio.content_binding.removed': 'studio.content_binding.removed.v1',
  'studio.draft.verified': 'studio.draft.verified.v1',
  'studio.draft.previewed': 'studio.draft.previewed.v1',
  'studio.publish.intent': 'studio.publish.intent.v1',
  'studio.publish.processed': 'studio.publish.processed.v1',
  'studio.publish.failed': 'studio.publish.failed.v1',
  'studio.publish.cancelled': 'studio.publish.cancelled.v1',
  'studio.asset.uploaded': 'studio.asset.uploaded.v1',
  'studio.asset.attached': 'studio.asset.attached.v1',
};