/** Experience Engine — Events */
export const EXPERIENCE_EVENTS = {
  EXPERIENCE_CREATED: 'experience.created',
  EXPERIENCE_UPDATED: 'experience.updated',
  EXPERIENCE_DELETED: 'experience.deleted',
  EXPERIENCE_ARCHIVED: 'experience.archived',
  EXPERIENCE_RESTORED: 'experience.restored',
  LAYOUT_CREATED: 'layout.created',
  LAYOUT_UPDATED: 'layout.updated',
  LAYOUT_PUBLISHED: 'layout.published',
  LAYOUT_CLONED: 'layout.cloned',
  LAYOUT_VALIDATED: 'layout.validated',
  HERO_CREATED: 'hero.created',
  HERO_UPDATED: 'hero.updated',
  HERO_PUBLISHED: 'hero.published',
  BANNER_CREATED: 'banner.created',
  BANNER_UPDATED: 'banner.updated',
  BANNER_PUBLISHED: 'banner.published',
  NAVIGATION_CREATED: 'navigation.created',
  NAVIGATION_UPDATED: 'navigation.updated',
  NAVIGATION_PUBLISHED: 'navigation.published',
  DASHBOARD_CREATED: 'dashboard.created',
  DASHBOARD_UPDATED: 'dashboard.updated',
  DASHBOARD_PUBLISHED: 'dashboard.published',
  SEARCH_EXPERIENCE_CREATED: 'searchExperience.created',
  SEARCH_EXPERIENCE_UPDATED: 'searchExperience.updated',
  SEARCH_EXPERIENCE_PUBLISHED: 'searchExperience.published',
  PATTERN_PUBLISHED: 'pattern.published',
  PATTERN_CLONED: 'pattern.cloned',
  UX_SCORED: 'ux.scored',
  UX_VALIDATED: 'ux.validated',
} as const;

export type ExperienceEventType = typeof EXPERIENCE_EVENTS[keyof typeof EXPERIENCE_EVENTS];

export const EXPERIENCE_EVENT_SCHEMAS: Record<ExperienceEventType, string> = {
  'experience.created': 'experience.created.v1',
  'experience.updated': 'experience.updated.v1',
  'experience.deleted': 'experience.deleted.v1',
  'experience.archived': 'experience.archived.v1',
  'experience.restored': 'experience.restored.v1',
  'layout.created': 'layout.created.v1',
  'layout.updated': 'layout.updated.v1',
  'layout.published': 'layout.published.v1',
  'layout.cloned': 'layout.cloned.v1',
  'layout.validated': 'layout.validated.v1',
  'hero.created': 'hero.created.v1',
  'hero.updated': 'hero.updated.v1',
  'hero.published': 'hero.published.v1',
  'banner.created': 'banner.created.v1',
  'banner.updated': 'banner.updated.v1',
  'banner.published': 'banner.published.v1',
  'navigation.created': 'navigation.created.v1',
  'navigation.updated': 'navigation.updated.v1',
  'navigation.published': 'navigation.published.v1',
  'dashboard.created': 'dashboard.created.v1',
  'dashboard.updated': 'dashboard.updated.v1',
  'dashboard.published': 'dashboard.published.v1',
  'searchExperience.created': 'searchExperience.created.v1',
  'searchExperience.updated': 'searchExperience.updated.v1',
  'searchExperience.published': 'searchExperience.published.v1',
  'pattern.published': 'pattern.published.v1',
  'pattern.cloned': 'pattern.cloned.v1',
  'ux.scored': 'ux.scored.v1',
  'ux.validated': 'ux.validated.v1',
};
