/**
 * Core SDK 공통 타입
 */

export type EngineName =
  | 'identity'
  | 'communication'
  | 'authorization'
  | 'user'
  | 'address'
  | 'organization'
  | 'catalog'
  | 'pricing'
  | 'notification'
  | 'event-bus'
  | 'media'
  | 'cms'
  | 'booking'
  | 'payment'
  | 'billing'
  | 'review'
  | 'analytics'
  | 'ai'
  | 'workflow'
  | 'universal-core'
  | 'policy'
  | 'core-sdk'
  | 'platform-compatibility'
  | 'platform-guardian'
  | 'platform-validation'
  | 'query'
  | 'search'
  | 'release-manager'
  | 'package-manager'
  | 'runtime'
  | 'experience'
  | 'theme'
  | 'creative-intelligence'
  | 'creative-knowledge'
  | 'learning';
