/** Creative Intelligence Engine RC2 — Events */
export const CREATIVE_EVENTS = {
  ART_DIRECTION_CREATED: 'ci.art_direction.created',
  ART_DIRECTION_ACTIVATED: 'ci.art_direction.activated',
  FIRST_IMPRESSION_REVIEWED: 'ci.first_impression.reviewed',
  PREMIUM_REVIEWED: 'ci.premium.reviewed',
  LUXURY_REVIEWED: 'ci.luxury.reviewed',
  VISUAL_HIERARCHY_REVIEWED: 'ci.visual_hierarchy.reviewed',
  WHITESPACE_REVIEWED: 'ci.whitespace.reviewed',
  TYPOGRAPHY_REVIEWED: 'ci.typography.reviewed',
  PHOTOGRAPHY_REVIEWED: 'ci.photography.reviewed',
  COMPOSITION_REVIEWED: 'ci.composition.reviewed',
  SCROLL_REVIEWED: 'ci.scroll.reviewed',
  MICRO_INTERACTION_REVIEWED: 'ci.micro_interaction.reviewed',
  VISUAL_CONSISTENCY_REVIEWED: 'ci.visual_consistency.reviewed',
  BRAND_EXPRESSION_REVIEWED: 'ci.brand_expression.reviewed',
  EMOTIONAL_JOURNEY_REVIEWED: 'ci.emotional_journey.reviewed',
  CONVERSION_REVIEWED: 'ci.conversion.reviewed',
  AI_SMELL_DETECTED: 'ci.ai_smell.detected',
  DESIGN_CRITIQUE_GENERATED: 'ci.design_critique.generated',
  DESIGN_RECOMMENDATION_GENERATED: 'ci.design_recommendation.generated',
  CREATIVE_APPROVED: 'ci.creative.approved',
  CREATIVE_REJECTED: 'ci.creative.rejected',
  ART_DIRECTION_REPORT: 'ci.report.art_direction',
  PREMIUM_REPORT: 'ci.report.premium',
  LUXURY_REPORT: 'ci.report.luxury',
  THREE_SECOND_REPORT: 'ci.report.three_second',
  CREATIVE_REVIEW_REPORT: 'ci.report.creative_review',
  DESIGN_CRITIQUE_REPORT: 'ci.report.design_critique',
  DESIGN_RECOMMENDATION_REPORT: 'ci.report.design_recommendation',
} as const;

export type CreativeEventType = typeof CREATIVE_EVENTS[keyof typeof CREATIVE_EVENTS];

export const CREATIVE_EVENT_SCHEMAS: Record<CreativeEventType, string> = {
  'ci.art_direction.created': 'ci.art_direction.created.v1',
  'ci.art_direction.activated': 'ci.art_direction.activated.v1',
  'ci.first_impression.reviewed': 'ci.first_impression.reviewed.v1',
  'ci.premium.reviewed': 'ci.premium.reviewed.v1',
  'ci.luxury.reviewed': 'ci.luxury.reviewed.v1',
  'ci.visual_hierarchy.reviewed': 'ci.visual_hierarchy.reviewed.v1',
  'ci.whitespace.reviewed': 'ci.whitespace.reviewed.v1',
  'ci.typography.reviewed': 'ci.typography.reviewed.v1',
  'ci.photography.reviewed': 'ci.photography.reviewed.v1',
  'ci.composition.reviewed': 'ci.composition.reviewed.v1',
  'ci.scroll.reviewed': 'ci.scroll.reviewed.v1',
  'ci.micro_interaction.reviewed': 'ci.micro_interaction.reviewed.v1',
  'ci.visual_consistency.reviewed': 'ci.visual_consistency.reviewed.v1',
  'ci.brand_expression.reviewed': 'ci.brand_expression.reviewed.v1',
  'ci.emotional_journey.reviewed': 'ci.emotional_journey.reviewed.v1',
  'ci.conversion.reviewed': 'ci.conversion.reviewed.v1',
  'ci.ai_smell.detected': 'ci.ai_smell.detected.v1',
  'ci.design_critique.generated': 'ci.design_critique.generated.v1',
  'ci.design_recommendation.generated': 'ci.design_recommendation.generated.v1',
  'ci.creative.approved': 'ci.creative.approved.v1',
  'ci.creative.rejected': 'ci.creative.rejected.v1',
  'ci.report.art_direction': 'ci.report.art_direction.v1',
  'ci.report.premium': 'ci.report.premium.v1',
  'ci.report.luxury': 'ci.report.luxury.v1',
  'ci.report.three_second': 'ci.report.three_second.v1',
  'ci.report.creative_review': 'ci.report.creative_review.v1',
  'ci.report.design_critique': 'ci.report.design_critique.v1',
  'ci.report.design_recommendation': 'ci.report.design_recommendation.v1',
};